name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: avsm/setup-ocaml@master
      with:
        ocaml-version: 4.09.0
    - name: "Setup other ocaml dependencies"
      run: opam install ocamlbuild ounit extlib
    - name: "Move ocaml dependencies to /usr/local/bin/"
      run: sudo cp /home/runner/.opam/4.09.0/bin/* /usr/local/bin/
    - name: Install docker, valgrind, and nasm
      run: sudo apt-get install -y docker nasm valgrind clang-8
    - name: Disable ASLR
      run: echo 0 | sudo tee /proc/sys/kernel/randomize_va_space
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v1
    - name: Deploy
      run: |
        make clean 
        make test 
        ./test
